name: face_form_detect
description: Face form detect
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  google_mlkit_face_detection: ^0.3.0
  image_picker:
  camera: ^0.10.0
  rxdart: ^0.27.4
  ml_algo: ^16.15.2
  screenshot: ^1.2.3
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  fluttertoast: ^8.0.9
  file_picker: ^5.0.1
  share_extend: ^2.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
